# Generated by Django 4.1.7 on 2023-03-29 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("bin", models.CharField(max_length=64)),
                ("email_block", models.CharField(max_length=64)),
                ("organization_type", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("second_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.CharField(max_length=64, unique=True)),
                ("phone_number", models.TextField(blank=True, null=True, unique=True)),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("birth_date", models.DateField(null=True)),
                ("password", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
                    ),
                ),
            ],
        ),
    ]
