# Generated by Django 4.1.7 on 2023-03-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableEmailDomens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domen", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("bin", models.CharField(max_length=64)),
                ("email_block", models.CharField(max_length=64)),
                (
                    "organization_type",
                    models.CharField(
                        choices=[
                            ("None", "Выберите должность"),
                            ("c", "Сотрудник Компании"),
                            ("i", "Сотрудник Института"),
                            ("u", "Сотрудник Университета"),
                            ("s", "Студент"),
                        ],
                        max_length=64,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("second_name", models.CharField(blank=True, max_length=64, null=True)),
                ("last_name", models.CharField(max_length=64)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.TextField(blank=True, null=True, unique=True)),
                (
                    "nickname",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("password", models.CharField(max_length=64)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="UserData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainapp.user"
                    ),
                ),
            ],
        ),
    ]
