# Generated by Django 4.1.7 on 2023-03-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="organization_type",
            field=models.CharField(
                choices=[
                    ("None", "Выберите должность"),
                    ("c", "Сотрудник Компании"),
                    ("i", "Сотрудник Института"),
                    ("u", "Сотрудник Университета"),
                    ("s", "Студент"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="birth_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=64),
        ),
    ]
