# Generated by Django 4.1.7 on 2023-03-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_user_birth_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("bin", models.CharField(max_length=64)),
                ("email_block", models.CharField(max_length=64)),
                ("organization_type", models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name="user",
            name="second_name",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
