# Generated by Django 4.1.7 on 2023-04-01 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_organization_user_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="staff",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="UserAdditionalData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.IntegerField(
                        blank=True, default=0, null=True, verbose_name="score"
                    ),
                ),
                (
                    "gpa",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="gpa"
                    ),
                ),
                ("about", models.TextField(blank=True)),
                ("score_is_visible", models.BooleanField(default=True)),
                ("gpa_is_visible", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
