# Generated by Django 4.1.7 on 2023-03-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_alter_organization_organization_type_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableEmailDomens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("domen", models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
