# Generated by Django 4.1.7 on 2023-04-01 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_organization_staff_useradditionaldata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useradditionaldata",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
